"""Fix User relationships and add VCard link

Revision ID: 03236c4a4a2c
Revises: 8cf178bac81b
Create Date: 2025-10-18 21:07:10.786662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03236c4a4a2c'
down_revision: Union[str, Sequence[str], None] = '8cf178bac81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=255), nullable=True),
    sa.Column('color_fg', sa.String(length=10), nullable=True),
    sa.Column('color_bg', sa.String(length=10), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('qr_size', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('dynamic_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dynamic_url')
    )
    op.create_index(op.f('ix_vcards_id'), 'vcards', ['id'], unique=False)
    op.alter_column('qr_codes', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('qr_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('ix_vcards_id'), table_name='vcards')
    op.drop_table('vcards')
    # ### end Alembic commands ###
