"""Remove old QR sub-models

Revision ID: 2453d94b3e55
Revises: 74e5ad6a2684
Create Date: 2025-11-09 12:39:24.985210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2453d94b3e55'
down_revision: Union[str, Sequence[str], None] = '74e5ad6a2684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
