"""Add qr_content_versions

Revision ID: 3efdf521b1c3
Revises: 413758a984fd
Create Date: 2025-11-05 14:55:26.804970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efdf521b1c3'
down_revision: Union[str, Sequence[str], None] = '413758a984fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'qr_urls', ['public_id'])
    op.create_unique_constraint(None, 'qr_wifi', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_wifi', type_='unique')
    op.drop_constraint(None, 'qr_urls', type_='unique')
    # ### end Alembic commands ###
