"""Check all models

Revision ID: 413758a984fd
Revises: 47ffe360122e
Create Date: 2025-11-05 08:59:31.029545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '413758a984fd'
down_revision: Union[str, Sequence[str], None] = '47ffe360122e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_payment', 'currency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
    op.add_column('qr_products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('qr_products', 'public_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('qr_products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('qr_scans', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.alter_column('qr_scans', 'qr_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_scans', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_qr_scans_qr_id'), 'qr_scans', ['qr_id'], unique=False)
    op.drop_index('ix_qr_urls_id', table_name='qr_urls')
    op.drop_index('ix_qr_urls_public_id', table_name='qr_urls')
    op.create_index('ix_qr_urls_public_id', 'qr_urls', ['public_id'], unique=False)
    op.drop_index('ix_qr_wifi_public_id', table_name='qr_wifi')
    op.create_index('ix_qr_wifi_public_id', 'qr_wifi', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qr_wifi_public_id', table_name='qr_wifi')
    op.create_index('ix_qr_wifi_public_id', 'qr_wifi', ['public_id'], unique=True)
    op.drop_index('ix_qr_urls_public_id', table_name='qr_urls')
    op.create_index('ix_qr_urls_public_id', 'qr_urls', ['public_id'], unique=True)
    op.create_index('ix_qr_urls_id', 'qr_urls', ['id'], unique=False)
    op.drop_index(op.f('ix_qr_scans_qr_id'), table_name='qr_scans')
    op.alter_column('qr_scans', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('qr_scans', 'qr_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('qr_scans', 'user_agent')
    op.alter_column('qr_products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('qr_products', 'public_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_column('qr_products', 'updated_at')
    op.alter_column('qr_payment', 'currency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
    # ### end Alembic commands ###
