"""Add all QR type tables

Revision ID: 47ffe360122e
Revises: 52d1d8e0e040
Create Date: 2025-11-05 08:35:00.292793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ffe360122e'
down_revision: Union[str, Sequence[str], None] = '52d1d8e0e040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_email_public_id'), 'qr_email', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_email_qr_id'), 'qr_email', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_email_user_id'), 'qr_email', ['user_id'], unique=False)
    op.create_table('qr_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_event_public_id'), 'qr_event', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_event_qr_id'), 'qr_event', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_event_user_id'), 'qr_event', ['user_id'], unique=False)
    op.create_table('qr_geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_geo_public_id'), 'qr_geo', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_geo_qr_id'), 'qr_geo', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_geo_user_id'), 'qr_geo', ['user_id'], unique=False)
    op.create_table('qr_multilink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('links_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_multilink_public_id'), 'qr_multilink', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_multilink_qr_id'), 'qr_multilink', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_multilink_user_id'), 'qr_multilink', ['user_id'], unique=False)
    op.create_table('qr_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_payment_public_id'), 'qr_payment', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_payment_qr_id'), 'qr_payment', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_payment_user_id'), 'qr_payment', ['user_id'], unique=False)
    op.create_table('qr_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_phone_public_id'), 'qr_phone', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_phone_qr_id'), 'qr_phone', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_phone_user_id'), 'qr_phone', ['user_id'], unique=False)
    op.create_table('qr_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_sms_public_id'), 'qr_sms', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_sms_qr_id'), 'qr_sms', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_sms_user_id'), 'qr_sms', ['user_id'], unique=False)
    op.create_table('qr_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_social_public_id'), 'qr_social', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_social_qr_id'), 'qr_social', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_social_user_id'), 'qr_social', ['user_id'], unique=False)
    op.create_table('qr_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('destination_url', sa.String(length=2048), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_urls_id'), 'qr_urls', ['id'], unique=False)
    op.create_index(op.f('ix_qr_urls_public_id'), 'qr_urls', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_urls_qr_id'), 'qr_urls', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_urls_user_id'), 'qr_urls', ['user_id'], unique=False)
    op.create_table('qr_wifi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('ssid', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('encryption', sa.String(length=20), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_wifi_public_id'), 'qr_wifi', ['public_id'], unique=True)
    op.create_index(op.f('ix_qr_wifi_qr_id'), 'qr_wifi', ['qr_id'], unique=False)
    op.create_index(op.f('ix_qr_wifi_user_id'), 'qr_wifi', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_wifi_user_id'), table_name='qr_wifi')
    op.drop_index(op.f('ix_qr_wifi_qr_id'), table_name='qr_wifi')
    op.drop_index(op.f('ix_qr_wifi_public_id'), table_name='qr_wifi')
    op.drop_table('qr_wifi')
    op.drop_index(op.f('ix_qr_urls_user_id'), table_name='qr_urls')
    op.drop_index(op.f('ix_qr_urls_qr_id'), table_name='qr_urls')
    op.drop_index(op.f('ix_qr_urls_public_id'), table_name='qr_urls')
    op.drop_index(op.f('ix_qr_urls_id'), table_name='qr_urls')
    op.drop_table('qr_urls')
    op.drop_index(op.f('ix_qr_social_user_id'), table_name='qr_social')
    op.drop_index(op.f('ix_qr_social_qr_id'), table_name='qr_social')
    op.drop_index(op.f('ix_qr_social_public_id'), table_name='qr_social')
    op.drop_table('qr_social')
    op.drop_index(op.f('ix_qr_sms_user_id'), table_name='qr_sms')
    op.drop_index(op.f('ix_qr_sms_qr_id'), table_name='qr_sms')
    op.drop_index(op.f('ix_qr_sms_public_id'), table_name='qr_sms')
    op.drop_table('qr_sms')
    op.drop_index(op.f('ix_qr_phone_user_id'), table_name='qr_phone')
    op.drop_index(op.f('ix_qr_phone_qr_id'), table_name='qr_phone')
    op.drop_index(op.f('ix_qr_phone_public_id'), table_name='qr_phone')
    op.drop_table('qr_phone')
    op.drop_index(op.f('ix_qr_payment_user_id'), table_name='qr_payment')
    op.drop_index(op.f('ix_qr_payment_qr_id'), table_name='qr_payment')
    op.drop_index(op.f('ix_qr_payment_public_id'), table_name='qr_payment')
    op.drop_table('qr_payment')
    op.drop_index(op.f('ix_qr_multilink_user_id'), table_name='qr_multilink')
    op.drop_index(op.f('ix_qr_multilink_qr_id'), table_name='qr_multilink')
    op.drop_index(op.f('ix_qr_multilink_public_id'), table_name='qr_multilink')
    op.drop_table('qr_multilink')
    op.drop_index(op.f('ix_qr_geo_user_id'), table_name='qr_geo')
    op.drop_index(op.f('ix_qr_geo_qr_id'), table_name='qr_geo')
    op.drop_index(op.f('ix_qr_geo_public_id'), table_name='qr_geo')
    op.drop_table('qr_geo')
    op.drop_index(op.f('ix_qr_event_user_id'), table_name='qr_event')
    op.drop_index(op.f('ix_qr_event_qr_id'), table_name='qr_event')
    op.drop_index(op.f('ix_qr_event_public_id'), table_name='qr_event')
    op.drop_table('qr_event')
    op.drop_index(op.f('ix_qr_email_user_id'), table_name='qr_email')
    op.drop_index(op.f('ix_qr_email_qr_id'), table_name='qr_email')
    op.drop_index(op.f('ix_qr_email_public_id'), table_name='qr_email')
    op.drop_table('qr_email')
    # ### end Alembic commands ###
