"""fix QRProduct and add design fields

Revision ID: 4aef93856b9c
Revises: 6e61a736e50a
Create Date: 2025-11-08 19:17:15.085212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4aef93856b9c'
down_revision: Union[str, Sequence[str], None] = '6e61a736e50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_products', sa.Column('style', sa.String(length=50), nullable=True))
    op.add_column('qr_products', sa.Column('fg_color', sa.String(length=20), nullable=True))
    op.add_column('qr_products', sa.Column('bg_color', sa.String(length=20), nullable=True))
    op.add_column('qr_products', sa.Column('qr_size', sa.Integer(), nullable=True))
    op.alter_column('qr_products', 'link',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('qr_products', 'image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('qr_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('qr_products', 'image_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('qr_products', 'link',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.drop_column('qr_products', 'qr_size')
    op.drop_column('qr_products', 'bg_color')
    op.drop_column('qr_products', 'fg_color')
    op.drop_column('qr_products', 'style')
    # ### end Alembic commands ###
