"""Clean: remove old QR models

Revision ID: 5b06afe476a3
Revises: 2453d94b3e55
Create Date: 2025-11-09 12:47:38.315103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b06afe476a3'
down_revision: Union[str, Sequence[str], None] = '2453d94b3e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=False),
    sa.Column('qr_type', sa.String(length=50), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_json', mysql.JSON(), nullable=False),
    sa.Column('version_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qr_content_versions_public_id'), 'qr_content_versions', ['public_id'], unique=False)
    op.create_table('qr_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_qr_products_id', table_name='qr_products')
    op.drop_index('ix_qr_products_public_id', table_name='qr_products')
    op.drop_table('qr_products')
    op.drop_index('ix_qr_wifi_public_id', table_name='qr_wifi')
    op.drop_index('ix_qr_wifi_qr_id', table_name='qr_wifi')
    op.drop_index('ix_qr_wifi_user_id', table_name='qr_wifi')
    op.drop_index('public_id', table_name='qr_wifi')
    op.drop_table('qr_wifi')
    op.drop_index('ix_qr_urls_public_id', table_name='qr_urls')
    op.drop_index('ix_qr_urls_qr_id', table_name='qr_urls')
    op.drop_index('ix_qr_urls_user_id', table_name='qr_urls')
    op.drop_index('public_id', table_name='qr_urls')
    op.drop_table('qr_urls')
    op.drop_index('ix_qr_payment_public_id', table_name='qr_payment')
    op.drop_index('ix_qr_payment_qr_id', table_name='qr_payment')
    op.drop_index('ix_qr_payment_user_id', table_name='qr_payment')
    op.drop_table('qr_payment')
    op.drop_index('ix_qr_multilink_public_id', table_name='qr_multilink')
    op.drop_index('ix_qr_multilink_qr_id', table_name='qr_multilink')
    op.drop_index('ix_qr_multilink_user_id', table_name='qr_multilink')
    op.drop_table('qr_multilink')
    op.drop_index('ix_qr_event_public_id', table_name='qr_event')
    op.drop_index('ix_qr_event_qr_id', table_name='qr_event')
    op.drop_index('ix_qr_event_user_id', table_name='qr_event')
    op.drop_table('qr_event')
    op.drop_index('ix_qr_geo_public_id', table_name='qr_geo')
    op.drop_index('ix_qr_geo_qr_id', table_name='qr_geo')
    op.drop_index('ix_qr_geo_user_id', table_name='qr_geo')
    op.drop_table('qr_geo')
    op.drop_index('dynamic_url', table_name='vcards')
    op.drop_index('ix_vcards_id', table_name='vcards')
    op.drop_table('vcards')
    op.drop_index('ix_qr_sms_public_id', table_name='qr_sms')
    op.drop_index('ix_qr_sms_qr_id', table_name='qr_sms')
    op.drop_index('ix_qr_sms_user_id', table_name='qr_sms')
    op.drop_table('qr_sms')
    op.drop_index('ix_qr_social_public_id', table_name='qr_social')
    op.drop_index('ix_qr_social_qr_id', table_name='qr_social')
    op.drop_index('ix_qr_social_user_id', table_name='qr_social')
    op.drop_table('qr_social')
    op.drop_index('ix_qr_email_public_id', table_name='qr_email')
    op.drop_index('ix_qr_email_qr_id', table_name='qr_email')
    op.drop_index('ix_qr_email_user_id', table_name='qr_email')
    op.drop_table('qr_email')
    op.drop_index('ix_qr_phone_public_id', table_name='qr_phone')
    op.drop_index('ix_qr_phone_qr_id', table_name='qr_phone')
    op.drop_index('ix_qr_phone_user_id', table_name='qr_phone')
    op.drop_table('qr_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_phone',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_phone_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_phone_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_phone_user_id', 'qr_phone', ['user_id'], unique=False)
    op.create_index('ix_qr_phone_qr_id', 'qr_phone', ['qr_id'], unique=False)
    op.create_index('ix_qr_phone_public_id', 'qr_phone', ['public_id'], unique=True)
    op.create_table('qr_email',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=320), nullable=False),
    sa.Column('subject', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('body', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_email_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_email_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_email_user_id', 'qr_email', ['user_id'], unique=False)
    op.create_index('ix_qr_email_qr_id', 'qr_email', ['qr_id'], unique=False)
    op.create_index('ix_qr_email_public_id', 'qr_email', ['public_id'], unique=True)
    op.create_table('qr_social',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=False),
    sa.Column('label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_social_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_social_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_social_user_id', 'qr_social', ['user_id'], unique=False)
    op.create_index('ix_qr_social_qr_id', 'qr_social', ['qr_id'], unique=False)
    op.create_index('ix_qr_social_public_id', 'qr_social', ['public_id'], unique=True)
    op.create_table('qr_sms',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_sms_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_sms_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_sms_user_id', 'qr_sms', ['user_id'], unique=False)
    op.create_index('ix_qr_sms_qr_id', 'qr_sms', ['qr_id'], unique=False)
    op.create_index('ix_qr_sms_public_id', 'qr_sms', ['public_id'], unique=True)
    op.create_table('vcards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('organization', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('website', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('linkedin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('whatsapp', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('color_fg', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('color_bg', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('logo_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('qr_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('dynamic_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vcards_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vcards_id', 'vcards', ['id'], unique=False)
    op.create_index('dynamic_url', 'vcards', ['dynamic_url'], unique=True)
    op.create_table('qr_geo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('label', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_geo_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_geo_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_geo_user_id', 'qr_geo', ['user_id'], unique=False)
    op.create_index('ix_qr_geo_qr_id', 'qr_geo', ['qr_id'], unique=False)
    op.create_index('ix_qr_geo_public_id', 'qr_geo', ['public_id'], unique=True)
    op.create_table('qr_event',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('start', mysql.DATETIME(), nullable=False),
    sa.Column('end', mysql.DATETIME(), nullable=False),
    sa.Column('all_day', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_event_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_event_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_event_user_id', 'qr_event', ['user_id'], unique=False)
    op.create_index('ix_qr_event_qr_id', 'qr_event', ['qr_id'], unique=False)
    op.create_index('ix_qr_event_public_id', 'qr_event', ['public_id'], unique=True)
    op.create_table('qr_multilink',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('bio', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('links_json', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_multilink_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_multilink_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_multilink_user_id', 'qr_multilink', ['user_id'], unique=False)
    op.create_index('ix_qr_multilink_qr_id', 'qr_multilink', ['qr_id'], unique=False)
    op.create_index('ix_qr_multilink_public_id', 'qr_multilink', ['public_id'], unique=True)
    op.create_table('qr_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('recipient', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('iban', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=34), nullable=True),
    sa.Column('bic', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('currency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('purpose', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_payment_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_payment_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_payment_user_id', 'qr_payment', ['user_id'], unique=False)
    op.create_index('ix_qr_payment_qr_id', 'qr_payment', ['qr_id'], unique=False)
    op.create_index('ix_qr_payment_public_id', 'qr_payment', ['public_id'], unique=True)
    op.create_table('qr_urls',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('destination_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=False),
    sa.Column('note', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_urls_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_urls_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('public_id', 'qr_urls', ['public_id'], unique=True)
    op.create_index('ix_qr_urls_user_id', 'qr_urls', ['user_id'], unique=False)
    op.create_index('ix_qr_urls_qr_id', 'qr_urls', ['qr_id'], unique=False)
    op.create_index('ix_qr_urls_public_id', 'qr_urls', ['public_id'], unique=False)
    op.create_table('qr_wifi',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ssid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('encryption', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], name='qr_wifi_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='qr_wifi_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('public_id', 'qr_wifi', ['public_id'], unique=True)
    op.create_index('ix_qr_wifi_user_id', 'qr_wifi', ['user_id'], unique=False)
    op.create_index('ix_qr_wifi_qr_id', 'qr_wifi', ['qr_id'], unique=False)
    op.create_index('ix_qr_wifi_public_id', 'qr_wifi', ['public_id'], unique=False)
    op.create_table('qr_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('qr_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('dynamic_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('fg_color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('bg_color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('qr_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_qr_products_public_id', 'qr_products', ['public_id'], unique=True)
    op.create_index('ix_qr_products_id', 'qr_products', ['id'], unique=False)
    op.drop_table('qr_history')
    op.drop_index(op.f('ix_qr_content_versions_public_id'), table_name='qr_content_versions')
    op.drop_table('qr_content_versions')
    # ### end Alembic commands ###
