"""Add QRProduct model

Revision ID: 5b11151474b2
Revises: ad090ff84480
Create Date: 2025-11-05 08:04:00.958459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b11151474b2'
down_revision: Union[str, Sequence[str], None] = 'ad090ff84480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_codes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('qr_codes', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('qr_codes', 'is_dynamic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('qr_codes', 'qr_size',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'style',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('qr_codes', 'theme_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('qr_codes', 'pattern_style',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('qr_codes', 'shadow',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('qr_codes', 'corner_radius',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'animated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('qr_codes', 'animation_speed',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'plan_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('users', 'plan_expiry',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'qr_limit',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'failed_logins',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    op.alter_column('vcards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vcards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'failed_logins',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'qr_limit',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'plan_expiry',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'plan_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('qr_codes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'animation_speed',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'animated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'corner_radius',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'shadow',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'pattern_style',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('qr_codes', 'theme_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('qr_codes', 'style',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('qr_codes', 'qr_size',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'is_dynamic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qr_codes', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###
