"""add qr_image and dynamic_url

Revision ID: 6e61a736e50a
Revises: dfa7e4a9a7dd
Create Date: 2025-11-08 18:15:12.894658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e61a736e50a'
down_revision: Union[str, Sequence[str], None] = 'dfa7e4a9a7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_products', sa.Column('qr_image', sa.String(length=500), nullable=True))
    op.add_column('qr_products', sa.Column('dynamic_url', sa.String(length=500), nullable=True))
    op.add_column('qr_products', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_products', 'user_id')
    op.drop_column('qr_products', 'dynamic_url')
    op.drop_column('qr_products', 'qr_image')
    # ### end Alembic commands ###
