"""Add QRCode.data JSON field

Revision ID: 74e5ad6a2684
Revises: 2a60a764efa1
Create Date: 2025-11-08 23:28:00.589014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e5ad6a2684'
down_revision: Union[str, Sequence[str], None] = '2a60a764efa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_codes', 'data')
    # ### end Alembic commands ###
