"""Create plans table

Revision ID: a37d81d50dd7
Revises: 6791f7bee625
Create Date: 2025-10-20 12:19:10.657778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37d81d50dd7'
down_revision: Union[str, Sequence[str], None] = '6791f7bee625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_scans_id'), 'qr_scans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_scans_id'), table_name='qr_scans')
    op.drop_table('qr_scans')
    # ### end Alembic commands ###
