"""Add theme_name and animation columns to qr_codes

Revision ID: b7a8fecfe870
Revises: 03236c4a4a2c
Create Date: 2025-10-19 19:35:09.464695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7a8fecfe870'
down_revision: Union[str, Sequence[str], None] = '03236c4a4a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('theme_name', sa.String(length=50), nullable=True))
    op.add_column('qr_codes', sa.Column('pattern_style', sa.String(length=50), nullable=True))
    op.add_column('qr_codes', sa.Column('gradient', sa.String(length=255), nullable=True))
    op.add_column('qr_codes', sa.Column('frame_style', sa.String(length=50), nullable=True))
    op.add_column('qr_codes', sa.Column('shadow', sa.Boolean(), nullable=True))
    op.add_column('qr_codes', sa.Column('corner_radius', sa.Integer(), nullable=True))
    op.add_column('qr_codes', sa.Column('svg_path', sa.String(length=255), nullable=True))
    op.add_column('qr_codes', sa.Column('animated', sa.Boolean(), nullable=True))
    op.add_column('qr_codes', sa.Column('animation_speed', sa.Integer(), nullable=True))
    op.alter_column('qr_codes', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_codes', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.drop_column('qr_codes', 'animation_speed')
    op.drop_column('qr_codes', 'animated')
    op.drop_column('qr_codes', 'svg_path')
    op.drop_column('qr_codes', 'corner_radius')
    op.drop_column('qr_codes', 'shadow')
    op.drop_column('qr_codes', 'frame_style')
    op.drop_column('qr_codes', 'gradient')
    op.drop_column('qr_codes', 'pattern_style')
    op.drop_column('qr_codes', 'theme_name')
    # ### end Alembic commands ###
